apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlinx-serialization'

ext {
    extName = 'NHentai'
    pkgNameSuffix = 'all.nhentai'
    extClass = '.NHFactory'
    extVersionCode = 54
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(":lib-randomua"))
    testImplementation("junit:junit:4.13.2")
}
